"""
main.py — FastAPI Server for the Smart India Travel Guide
==========================================================

This module exposes the deterministic semantic-network chatbot as a
RESTful API.  No external LLM or NLP service is required — every
answer is produced by graph traversal over the knowledge base defined
in ``data.py``.

Endpoints
---------
* ``POST /api/chat`` — accepts a user message and returns a structured
  JSON response containing the answer and the reasoning path.
* ``GET  /api/health`` — lightweight health-check / readiness probe.
* ``GET  /api/stats`` — returns graph statistics (node count, edge
  count, predicate types).

Run
---
::

    uvicorn main:app --reload --port 8000
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import AsyncIterator

from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field

from network import SemanticNetwork
from nlp import ChatProcessor

# ──────────────────────────────────────────────────────────────────────
#  Logging
# ──────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-7s | %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────
#  Application State  (initialized via lifespan)
# ──────────────────────────────────────────────────────────────────────
_network: SemanticNetwork | None = None
_processor: ChatProcessor | None = None


@asynccontextmanager
async def lifespan(application: FastAPI) -> AsyncIterator[None]:
    """Build the semantic network and chat processor at startup."""
    global _network, _processor  # noqa: PLW0603

    logger.info("Building semantic network from data.py …")
    _network = SemanticNetwork()
    _processor = ChatProcessor(network=_network)
    logger.info(
        "Startup complete — %d nodes, %d edges ready.",
        _network.node_count,
        _network.edge_count,
    )
    yield
    logger.info("Shutting down Smart India Travel Guide API.")


# ──────────────────────────────────────────────────────────────────────
#  FastAPI App
# ──────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Smart India Travel Guide",
    description=(
        "A deterministic, graph-powered travel chatbot API.  "
        "No LLMs — just pure symbolic reasoning over a semantic network "
        "of 20 Indian destinations."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Allow cross-origin requests (useful for frontend integration)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ──────────────────────────────────────────────────────────────────────
#  Pydantic Models
# ──────────────────────────────────────────────────────────────────────
class ChatRequest(BaseModel):
    """Incoming user message payload."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=500,
        examples=["Tell me about Goa"],
        description="The user's natural-language query.",
    )


class ChatResponseModel(BaseModel):
    """Structured API response returned to the client."""

    response: str = Field(
        ...,
        description="Human-readable answer generated by the reasoning engine.",
    )
    reasoning_path: list[str] = Field(
        default_factory=list,
        description=(
            "Ordered list of node labels traversed during inference, "
            "representing the explainable 'why' behind the answer."
        ),
    )


class StatsResponse(BaseModel):
    """Graph statistics payload."""

    nodes: int
    edges: int
    predicate_types: list[str]


class HealthResponse(BaseModel):
    """Health-check payload."""

    status: str = "ok"
    nodes_loaded: int = 0


# ──────────────────────────────────────────────────────────────────────
#  Endpoints
# ──────────────────────────────────────────────────────────────────────

@app.post(
    "/api/chat",
    response_model=ChatResponseModel,
    summary="Chat with the travel guide",
    tags=["Chat"],
)
async def chat(request: ChatRequest) -> ChatResponseModel:
    """Process a user message and return a reasoned response.

    The pipeline:
    1. **Clean** the input text (lowercase, strip punctuation).
    2. **Extract** entities by matching against the semantic network.
    3. **Classify** intent (forward / reverse / path / attribute / related).
    4. **Traverse** the graph to produce an answer and reasoning path.

    Raises
    ------
    HTTPException 503
        If the engine has not finished initializing.
    HTTPException 404
        If a referenced entity is not found in the knowledge base.
    HTTPException 500
        For any unexpected processing error.
    """
    if _processor is None:
        raise HTTPException(
            status_code=503,
            detail="The reasoning engine is still initializing. Try again shortly.",
        )

    try:
        result = _processor.process(request.message)
    except KeyError as exc:
        raise HTTPException(
            status_code=404,
            detail=f"Entity not found in the knowledge base: {exc}",
        ) from exc
    except Exception as exc:
        logger.exception("Unexpected error while processing message.")
        raise HTTPException(
            status_code=500,
            detail=f"Internal processing error: {exc}",
        ) from exc

    # Flatten the reasoning path into a readable list of node labels
    path_labels: list[str] = []
    if result.reasoning_path:
        path_labels.append(result.reasoning_path[0][0])  # first source
        for _, predicate, target in result.reasoning_path:
            path_labels.append(f"--[{predicate}]-->")
            path_labels.append(target)

    return ChatResponseModel(
        response=result.message,
        reasoning_path=path_labels,
    )


@app.get(
    "/api/health",
    response_model=HealthResponse,
    summary="Health check",
    tags=["System"],
)
async def health() -> HealthResponse:
    """Return the current health status of the API."""
    return HealthResponse(
        status="ok" if _network is not None else "initializing",
        nodes_loaded=_network.node_count if _network else 0,
    )


@app.get(
    "/api/stats",
    response_model=StatsResponse,
    summary="Graph statistics",
    tags=["System"],
)
async def stats() -> StatsResponse:
    """Return summary statistics about the loaded semantic network."""
    if _network is None:
        raise HTTPException(status_code=503, detail="Network not yet loaded.")

    return StatsResponse(
        nodes=_network.node_count,
        edges=_network.edge_count,
        predicate_types=sorted(_network.predicate_types),
    )


# ──────────────────────────────────────────────────────────────────────
#  Serve Frontend
# ──────────────────────────────────────────────────────────────────────
_INDEX_HTML = Path(__file__).parent / "index.html"


@app.get("/", response_class=HTMLResponse, include_in_schema=False)
async def serve_frontend() -> HTMLResponse:
    """Serve the chat UI at the root URL."""
    return HTMLResponse(content=_INDEX_HTML.read_text(encoding="utf-8"))
